### ISSUE TITLE
ascii

### ISSUE THREAD

**Issue by maschbd** [solute/pyramid_epfl#5]
The validator

class CurrencyValidation(object):

    def __init__(self):
        pass

    def __call__(self, form, field):
        regex = re.compile(unicode(r'^(\d*(\d\,?|\,\d{1,2}))$'), re.UNICODE)
        result = regex.match(str(field.data))
        if result is None:
            message="Invalid Currency Form"
            raise ValidationError(message)

prints "ascii" in 
{{ form.errors | join(' ') }}
if there is a € symbol in the entry field.

**Comment by JustusW** [comment]
Widgets and the old form have been deprecated, so this is probably no longer valid.
